[tool.poetry]
name = "tiendil_youtube_dl_utilities"
version = "0.1"
description = "Custom installation."
authors = ["Aliaksei Yaletski (Tiendil) <a.eletsky@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

youtube-dl = "2021.5.16"
