[tool.poetry]
name = "tiendil_docker_utilities"
version = "0.1"
description = "Custom installation."
authors = ["Aliaksei Yaletski (Tiendil) <a.eletsky@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

docker-compose = "^1.29"
